name: Caching and Artifacts
on: [workflow_dispatch]

jobs:
  use-axios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm run ci
      - name: Use axios
        uses: actions/github-script@v7
        with:
          script: |
            const axios = require('axios')
            const res = await axios('https://jsonplaceholder.typicode.com/posts/1', { headers: { Accept: 'application/json' } })
            console.log('Axios response:', res.data)
