name: Environment variables
on: [push]

env:
  WORKFLOW_LEVEL_ENV: Available to everyone

jobs:
  env-vars-and-context:
    runs-on: ubuntu-latest
    env:
      JOB_LEVEL_ENV: Available to all the steps of this job
    steps:
      - name: Log env vars
        run: echo $GITHUB_REF
      - name: Log context
        run: echo '${{ github.ref }}'
      - name: Set env var
        run: |
          echo 'NEW_ENV_VAR=$(date)' >> '$GITHUB_ENV'
          echo 'JOB_LEVEL_ENV=$RANDOM' >> '$GITHUB_ENV'
      - name: Multiline env var
        run: |
          {
            echo 'JSON_RESPONSE<<EOF'
            curl https://www.google.com
            echo EOF
          } >> "$GITHUB_ENV"
      - name: Another multiline env var
        run: |
          DELIMITER=1234
          echo "RANDOM_JOKE<<$DELIMITER" >> "$GITHUB_ENV"
          echo "Here is a joke:" >> "$GITHUB_ENV"
          curl -s https://icanhazdadjoke.com/ >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "$DELIMITER" >> "$GITHUB_ENV"
      - name: Custom env var
        env:
          STEP_LEVEL_ENV: Available to only this step
        run: |
          echo '${{ env.STEP_LEVEL_ENV }}'
          echo $STEP_LEVEL_ENV
          echo $WORKFLOW_LEVEL_ENV
          echo $JOB_LEVEL_ENV
          echo $NEW_ENV_VAR
          echo $JSON_RESPONSE
          echo $RANDOM_JOKE
