name: Expressions and context
on: [push, pull_request, issues, workflow_dispatch]
run-name: "Expressions and context by @${{ github.actor }}, event: ${{ github.event_name }}"

jobs:
  using-expressions-and-context:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Expressions
        id: expressions
        run: |
          echo ${{ 'This is a string' }}
          echo ${{ true }}
          echo ${{ null }}
          echo ${{ 1 > 2 }}
          echo ${{ 'string' == 'STRING' }}
          echo ${{ true && false }}
          echo ${{ true || false }}
      - name: Dump contexts
        run: |
          echo '${{ toJson(github) }}'
          echo '${{ toJson(job) }}'
          echo '${{ toJson(secrets) }}'
          echo '${{ toJson(steps) }}'
          echo '${{ toJson(runner) }}'
