name: Matrix
on: [push]

jobs:
  node-matrix:
    continue-on-error: ${{ matrix.experimental == true }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18, 20, 22]
        include:
          - os: ubuntu-latest
            node-version: 20
            experimental: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Fail a step
        if: matrix.experimental == true
        run: exit 1
      - name: Initial node version
        run: node -v
      - name: Setup node via actions
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Final node version
        run: node -v
